### PR TITLE
node-rdiff 0.0.3 can't build with librsync >= 1.0.0

### PR DESCRIPTION
**Pull request by M-I**
With librsync 1.0.0, node-gyp gives this error:

  CXX(target) Release/obj.target/rdiff/rdiff.o
../rdiff.cc: In function 'rs_result signature(const char_, const char_)':
../rdiff.cc:214:75: error: cannot convert 'rs_stats_t\* {aka rs_stats_}' to 'rs_magic_number' for argument '5' to 'rs_result rs_sig_file(FILE_, FILE_, size_t, size_t, rs_magic_number, rs_stats_t_)'
   result = rs_sig_file(basis_file, sig_file, block_len, strong_len, &stats);
                                                                           ^
rdiff.target.mk:83: recipe for target 'Release/obj.target/rdiff/rdiff.o' failed
make: **\* [Release/obj.target/rdiff/rdiff.o] Error 1

### CODE REVIEW

**Comment by diorahman** [comment]
Thanks for this. I'll take a look at the implementation.

**Comment by M-I** [comment]
For now, it's only affecting bleeding-edge OSes (Arch Linux, etc.). OSX (via homebrew), debian and FreeBSD based distros still ship v0.9.7.

**Comment by diorahman** [comment]
@M-I please check the latest dist on npm https://github.com/diorahman/node-rdiff/commit/4e04a5b76d76321f5507422560874e4d40a01d6b :dancer: it works now

**Comment by M-I** [comment]
Building and passing tests on archlinux with librsync 1.0.0.
Nice ☺
