### ISSUE TITLE
Not building with npm version 3.5.3

### ISSUE THREAD

**Issue by FallingSnow** [diorahman/node-rdiff#3]
```
npm install --save rdiff                 

> rdiff@0.0.3 install /home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff
> node-gyp rebuild

make: Entering directory '/home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff/build'
  CXX(target) Release/obj.target/rdiff/rdiff.o
In file included from ../rdiff.h:9:0,
                 from ../rdiff.cc:1:
../../nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:319:17: note: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../../nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../../nan/nan.h:334:27: note: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:768:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../rdiff.h:9,
                 from ../rdiff.cc:1:
/home/ayrton/.node-gyp/5.5.0/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ayrton/.node-gyp/5.5.0/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../rdiff.h:9:0,
                 from ../rdiff.cc:1:
../../nan/nan.h:768:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../rdiff.h:9,
                 from ../rdiff.cc:1:
/home/ayrton/.node-gyp/5.5.0/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ayrton/.node-gyp/5.5.0/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../rdiff.h:9:0,
                 from ../rdiff.cc:1:
../../nan/nan.h:768:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:772:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../rdiff.cc: At global scope:
../rdiff.cc:167:28: error: ‘RS_DEFAULT_STRONG_LEN’ was not declared in this scope
 static size_t strong_len = RS_DEFAULT_STRONG_LEN;
                            ^
../rdiff.cc: In function ‘rs_result signature(const char*, const char*)’:
../rdiff.cc:214:75: error: cannot convert ‘rs_stats_t* {aka rs_stats*}’ to ‘rs_magic_number’ for argument ‘5’ to ‘rs_result rs_sig_file(FILE*, FILE*, size_t, size_t, rs_magic_number, rs_stats_t*)’
   result = rs_sig_file(basis_file, sig_file, block_len, strong_len, &stats);
                                                                           ^
rdiff.target.mk:90: recipe for target 'Release/obj.target/rdiff/rdiff.o' failed
make: *** [Release/obj.target/rdiff/rdiff.o] Error 1
make: Leaving directory '/home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.3-2-zen
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN FallenCloud@0.0.1 No description
npm WARN FallenCloud@0.0.1 No repository field.
npm WARN FallenCloud@0.0.1 No license field.
npm ERR! Linux 4.3.3-2-zen
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "rdiff"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! rdiff@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rdiff@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rdiff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rdiff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rdiff
npm ERR! There is likely additional logging output above

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ayrton/NetbeansProjects/FallenCloud/npm-debug.log
```
### output of /home/ayrton/NetbeansProjects/FallenCloud/npm-debug.log

http://pastebin.com/sm23ZJey

**Comment by diorahman** [comment]
Should upgrade the NAN version. I'll take a look at this. Thanks!

**Comment by FallingSnow** [comment]
Thanks!

**Comment by FallingSnow** [comment]
I've made some progress by updating NAN and changing a lot of the calls from Nan prefixes to Nan scoped (NanCallback to Nan::Callback). But I'm still running into a lot of errors that are simply far beyond my c++ skills, for example;

``` c++
/home/ayrton/.node-gyp/5.5.0/include/node/v8.h:2593:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/ayrton/.node-gyp/5.5.0/include/node/v8.h:2593:37: note:   candidate expects 3 arguments, 2 provided
../rdiff.cc:161:107: error: no matching function for call to ‘v8::Object::Set(Nan::imp::MaybeFactoryBase<v8::String>::return_t, v8::Local<v8::Function>)’
   exports->Set(Nan::New<String>("deltaSync"), Nan::New<FunctionTemplate>(GenerateDeltaSync)->GetFunction());
                                                                                                           ^
In file included from /home/ayrton/.node-gyp/5.5.0/include/node/v8.h:23:0,
                 from /home/ayrton/.node-gyp/5.5.0/include/node/node.h:42,
                 from ../rdiff.h:8,
                 from ../rdiff.cc:1:
/home/ayrton/.node-gyp/5.5.0/include/node/v8.h:2587:26: note: candidate: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/ayrton/.node-gyp/5.5.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
```

**Comment by diorahman** [comment]
@FallingSnow can you check the latest commit ? https://github.com/diorahman/node-rdiff/commit/ebfe9e0be3123586a13a2d66aced368607c1895b

I have published it on npm too.

**Comment by FallingSnow** [comment]
Looks like it works. Thanks! Any chance of it working with librsync 1.0.0+? It seems like it's only 1 or 2 errors.

``` c++
> rdiff@0.0.4 install /home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff
> node-gyp rebuild

make: Entering directory '/home/ayrton/NetbeansProjects/FallenCloud/node_modules/rdiff/build'
  CXX(target) Release/obj.target/rdiff/rdiff.o
../rdiff.cc:179:28: error: ‘RS_DEFAULT_STRONG_LEN’ was not declared in this scope
 static size_t strong_len = RS_DEFAULT_STRONG_LEN;
                            ^
../rdiff.cc: In function ‘rs_result signature(const char*, const char*)’:
../rdiff.cc:224:77: error: cannot convert ‘rs_stats_t* {aka rs_stats*}’ to ‘rs_magic_number’ for argument ‘5’ to ‘rs_result rs_sig_file(FILE*, FILE*, size_t, size_t, rs_magic_number, rs_stats_t*)’
     result = rs_sig_file(basis_file, sig_file, block_len, strong_len, &stats);
                                                                             ^
```

**Comment by diorahman** [comment]
Cool. Yeah, I want to upgrade it. Track it on https://github.com/diorahman/node-rdiff/issues/4
